"""chat models

Revision ID: 5efae6390b63
Revises: 
Create Date: 2026-04-11 15:18:49.457343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efae6390b63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('group_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('group_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_chat.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_message_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_message_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_message_timestamp'), ['timestamp'], unique=False)

    op.create_table('private_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('private_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_private_message_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_private_message_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_private_message_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_private_message_timestamp'))
        batch_op.drop_index(batch_op.f('ix_private_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_private_message_receiver_id'))

    op.drop_table('private_message')
    with op.batch_alter_table('group_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_message_timestamp'))
        batch_op.drop_index(batch_op.f('ix_group_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_group_message_group_id'))

    op.drop_table('group_message')
    op.drop_table('group_members')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('group_chat')
    # ### end Alembic commands ###
